### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Pushok\Response::__construct() must be of the type string, null given, called in 

### ISSUE THREAD

**Issue by jassimkm** [edamov/pushok#17] opened 2017-04-20 05:56 UTC
Hi ,
I am not a php developer so please help me with following error

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Pushok\Response::__construct() must be of the type string, null given, called in /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php on line 101 and defined in /Users/anargha/apnNew/vendor/edamov/pushok/src/Response.php:136
Stack trace:
#0 /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php(101): Pushok\Response->__construct(0, '', NULL)
#1 /Users/anargha/apnNew/test.php(43): Pushok\Client->push()
#2 {main}
  thrown in /Users/anargha/apnNew/vendor/edamov/pushok/src/Response.php on line 136

Fatal error: Uncaught TypeError: Argument 3 passed to Pushok\Response::__construct() must be of the type string, null given, called in /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php on line 101 and defined in /Users/anargha/apnNew/vendor/edamov/pushok/src/Response.php:136
Stack trace:
#0 /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php(101): Pushok\Response->__construct(0, '', NULL)
#1 /Users/anargha/apnNew/test.php(43): Pushok\Client->push()
#2 {main}
  thrown in /Users/anargha/apnNew/vendor/edamov/pushok/src/Response.php on line 136

**Comment by remcoanker** [comment] 2017-04-20 08:39
This error happens when the result is empty. Try to get the error from curl using 

`echo curl_error($handle);`

Add that line before [line 99 in Client.php](https://github.com/edamov/pushok/blob/b8218d646ecd7959dd17d1144a9f1b54077329bf/src/Client.php#L99).

In my case, this error was caused by timeouts when sending >200 notifications at once. #18 fixes this case.

**Comment by jassimkm** [comment] 2017-04-24 04:34
Hi @remcoanker 
Now its like this
 
No URL set!PHP Notice:  Undefined offset: 1 in /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php on line 101

Notice: Undefined offset: 1 in /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php on line 101
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Pushok\Response::__construct() must be of the type string, null given, called in /Users/anargha/apnNew/vendor/edamov/pushok/src/Client.php on line 103 and defined in /Users/anargha/apnNew/vendor/edamov/pushok/src/Response.php:136
Stack trace:

**Comment by remcoanker** [comment] 2017-04-24 12:32
Your curl error is `No URL set!`. 

This looks like the same issue as #9. Make sure you meet the requirements:

> PHP >= 7.0
lib-curl >= 7.46.0 (with http/2 support enabled)
lib-openssl >= 1.0.2e

Check the output of `phpinfo();` to see if you have it set up correctly.

**Comment by edamov** [comment] 2017-09-27 10:21
Yest, this issue is a duplicate of #9

**Closed as completed by edamov** 2017-09-27 10:21 UTC
Labels: duplicate
